server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
zuul:
  ribbon:
      eager-load:
        enabled: true
  prefix: /api
  routes:
    item-service: /item/** #路由到商品的微服务
    search-service: /search/** #路由到搜索微服务
    user-service: /user/** #路由到用户微服务
    auth-service: /auth/** #路由到授权微服务
    cart-service: /cart/** #路由到购物车微服务
    order-service: /order/** #路由到订单微服务
  host:
        connect-timeout-millis: 10000
        socket-timeout-millis: 60000
  add-host-header: true
  sensitive-headers:  #覆盖默认敏感头信息
leyou:
  jwt:
    pubKeyPath: E:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item

