server:
  port: 8084
spring:
  application:
    name: goods-web
  thymeleaf:
    cache: false
  rabbitmq:
      host: 192.168.72.130
      virtual-host: /leyou
      username: leyou
      password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.100:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期